In [4]:
import numpy as np
import matplotlib as plot
from sklearn.metrics import confusion_matrix

In [5]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
#x has 2 feature time spent walking ,time spent sitting 
y = np.array(([92], [86], [89]), dtype=float)
#y is  label with amount of  calorie burnt


In [11]:
pwd

'C:\\Users\\ms\\python_files'

In [6]:
# scale units
#X = X/np.amax(X, axis=0) # maximum of X array
#y = y/100
# the above step normalizes our data

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
xPredicted = np.array(([4,8]), dtype=float)


#Define input layer,hidden layer and output layer


X = X/np.amax(X, axis=0) # maximum of X array
xPredicted = xPredicted/np.amax(xPredicted, axis=0) # maximum of xPredicted (our input data for the prediction)
y = y/100 # 


In [10]:





class Neural_Network(object):
  
    def __init__(self):
        #parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer



    def forward(self, X):
           #forward propagation 
                self.z = np.dot(X, self.W1) # dot product of X (input) and first set of 3x2 weights
                self.z2 = self.sigmoid(self.z) # activation function
                self.z3 = np.dot(self.z2, self.W2) # dot product of hidden layer (z2) and second set of 3x1 weights
                o = self.sigmoid(self.z3) # final activation function
                return o


    def sigmoid(self, s):
          # activation function
        return 1/(1+np.exp(-s))


    #NN = Neural_Network()

                    #defining our output
        #o = NN.forward(X)

    #print ("Predicted Output: \n" + str(o))
    #print ("Actual Output: \n" + str(y))



    def sigmoidPrime(self, s):
    #derivative of sigmoid
     return s * (1 - s)





    def backward(self, X, y, o):
        # backward propagation
        self.o_error = y - o # error in output
        self.o_delta = self.o_error*self.sigmoidPrime(o) #  derivative of sigmoid to error

        self.z2_error = self.o_delta.dot(self.W2.T) # z2 error: how much our hidden layer weights contributed to output error
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2) # applying derivative of sigmoid to z2 error

        self.W1 += X.T.dot(self.z2_delta) # adjusting first set (input --> hidden) weights
        self.W2 += self.z2.T.dot(self.o_delta) # adjusting second set (hidden --> output) weights

    def train(self, X, y):
        o = self.forward(X)
        self.backward(X, y, o)

    def saveWeights(self):
        np.savetxt("w1.txt", self.W1, fmt="%s")
        np.savetxt("w2.txt", self.W2, fmt="%s")

    def predict(self):
        print ("Predicted data based on trained weights: ")
        print ("(Input (scaled): \n" + str(xPredicted))
        print ("Output: \n" + str(self.forward(xPredicted)))

NN = Neural_Network()
for i in range(100): # trains the NN 1,000 times
    print ("# " + str(i) + "\n")
    print ("Input (scaled): \n" + str(X))
    print ("Actual Output: \n" + str(y))
    print ("Predicted Output: \n" + str(NN.forward(X)))
    print ("Loss: \n" + str(np.mean(np.square(y - NN.forward(X))))) # mean sum squared loss
    print ("\n")
    NN.train(X, y)

NN.saveWeights()
NN.predict()





# 0

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.45949102]
 [0.44888037]
 [0.45714289]]
Loss: 
0.1894843801807272


# 1

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.57008016]
 [0.54503264]
 [0.57522794]]
Loss: 
0.10690992642898606


# 2

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.64794452]
 [0.61436395]
 [0.65768623]]
Loss: 
0.06277364783280635


# 3

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
[[0.69959865]
 [0.6615784 ]
 [0.71164763]]
Loss: 
0.03991915071672692


# 4

Input (scaled): 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.     